name: fe-diploma

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ["20.x"]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build
      run: npm run build
      
    - name: Configure Git credentials
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"

    - name: Deploy
      if: github.event_name == 'push' && contains(github.ref, 'refs/heads/main')
      run: |
        npm run deploy
      env:
        GH_TOKEN: ${{ secrets.GH_PAGES_TOKEN }}